version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: job_portal/Dockerfile
    volumes:
      - ./job_portal:/job_portal
      - /job_portal/.venv
    ports:
      - 80:8000
    networks:
      - job-portal-network
    env_file:
      - .env
    depends_on:
      db_postgres:
        condition: service_healthy

  db_postgres:
    image: postgres:15.3
    expose:
      - 5432
    networks:
      - job-portal-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pduran -d db_postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-dev
    networks:
      - job-portal-network
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
      - db_postgres
    restart: always

networks:
  job-portal-network:
    name: job-portal-network
    driver: bridge
